/*
 * ER/Studio 8.0 SQL Code Generation
 * Company :      -
 * Project :      der_igreja.dm1
 * Author :       D031092
 *
 * Date Created : Sunday, October 22, 2017 15:34:07
 * Target DBMS : Microsoft SQL Server 2008
 */


/* 
 * Zera Banco
 */ 
 /*

DROP TABLE PARTICIPANTES;
DROP TABLE PEDIDOORACAO;
DROP TABLE AGENDAPASTORAL;
DROP TABLE PROGRAMACAO;
DROP TABLE IGREJA;
DROP TABLE BAIXADUPLICATA;
DROP TABLE OCORRENCIAENTRANTE;
DROP TABLE DUPLICATA;
DROP TABLE CONTACORRENTE;
DROP TABLE EVENTOS;
DROP TABLE FORMAPAGAMENTO;
DROP TABLE INTEGRANTES;
DROP TABLE MENSAGEMSAINTE;
DROP TABLE MENSAGEMENTRANTE;
DROP TABLE MINISTERIOS;
DROP TABLE PARAMETROS;
DROP TABLE PLANOCONTA;
DROP TABLE POSTAGEM;
DROP TABLE TIPOMENSAGEM;
DROP TABLE TOPICO;
DROP TABLE USUARIO;
DROP TABLE BENEFICIARIO;
DROP TABLE PROFISSAO;

DROP SEQUENCE SEQ_AGENDAPASTORAL;
DROP SEQUENCE SEQ_PROFISSAO;
DROP SEQUENCE SEQ_PARTICIPANTES;
DROP SEQUENCE SEQ_PEDIDOORACAO;
DROP SEQUENCE SEQ_BAIXADUPLICATA;
DROP SEQUENCE SEQ_BENEFICIARIO;
DROP SEQUENCE SEQ_CONTACORRENTE;
DROP SEQUENCE SEQ_DUPLICATA;
DROP SEQUENCE SEQ_EVENTOS;
DROP SEQUENCE SEQ_FORMAPAGAMENTO;
DROP SEQUENCE SEQ_IGREJA;
DROP SEQUENCE SEQ_INTEGRANTES; 
DROP SEQUENCE SEQ_MENSAGEMENTRANTE;
DROP SEQUENCE SEQ_MENSAGEMSAINTE;
DROP SEQUENCE SEQ_MINISTERIOS;
DROP SEQUENCE SEQ_PARAMETROS;
DROP SEQUENCE SEQ_PLANOCONTA;
DROP SEQUENCE SEQ_POSTAGEM; 
DROP SEQUENCE SEQ_PROGRAMACAO;
DROP SEQUENCE SEQ_TIPOMENSAGEM;
DROP SEQUENCE SEQ_TOPICO;
DROP SEQUENCE SEQ_USUARIO;
DROP SEQUENCE SEQ_OCORRENCIAENTRANTE;
*/

/* 
 * TABLE: AGENDAPASTORAL 
 */


CREATE TABLE AGENDAPASTORAL(
    ID                varchar(36) NOT NULL,
    EVENTO            varchar(5000)    NULL,
    DATA              date             NULL,
    HORARIOINICIAL    time(7)          NULL,
    HORARIOFINAL      time(7)          NULL,
    LOCAL             varchar(300)     NULL,
    PRIVADO           varchar(1)       DEFAULT '0' NULL,
    CONSTRAINT PK_AGENDAPASTORAL PRIMARY KEY NONCLUSTERED (ID)
)
go



IF OBJECT_ID('AGENDAPASTORAL') IS NOT NULL
    PRINT '<<< CREATED TABLE AGENDAPASTORAL >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE AGENDAPASTORAL >>>'
go

/* 
 * TABLE: BAIXADUPLICATA 
 */

CREATE TABLE BAIXADUPLICATA(
	ID                varchar(36) NOT NULL,
    CODDUPLICATA         varchar(36)               NOT NULL,
    CODFORMAPAGAMENTO    varchar(36)               NOT NULL,
    VALORPAGO            numeric(12, 2)    DEFAULT 0 NOT NULL,
    DATAPAGAMENTO        date              DEFAULT getdate() NOT NULL,
    CONSTRAINT PK_BAIXADUPLICATA PRIMARY KEY NONCLUSTERED (ID)
)
go



IF OBJECT_ID('BAIXADUPLICATA') IS NOT NULL
    PRINT '<<< CREATED TABLE BAIXADUPLICATA >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE BAIXADUPLICATA >>>'
go

/* 
 * TABLE: BENEFICIARIO 
 */

CREATE TABLE BENEFICIARIO(
	ID                   varchar(36) NOT NULL,
    NOME                 varchar(100)    NOT NULL,
    EMAIL                varchar(100)    NULL,
    TELEFONE             varchar(16)     NULL,
    CELULAR               varchar(16)     NULL,
    DATACADASTRO         date            DEFAULT getdate() NOT NULL,
    TIPOBENEFICIARIO     varchar(10)     NULL,
    ATIVO                varchar(1)      DEFAULT '1' NOT NULL,
    TIPOPESSOA           varchar(1)      DEFAULT '0' NULL,
    DOCUMENTOI           varchar(18)     NULL,
    DOCUMENTOII          varchar(18)     NULL,
    ENDERECO             varchar(60)     NULL,
    NUMERO               varchar(10)     NULL,
    BAIRRO               varchar(60)     NULL,
    CIDADE               varchar(60)     NULL,
    UF                   varchar(2)      NOT NULL,
    AUTORIZAPROFISSAO    varchar(1)      NULL,
    CODPROFISSAO         varchar(36)             NULL,
    CONSTRAINT PK_BENEFICIARIO PRIMARY KEY NONCLUSTERED (ID)
)
go



IF OBJECT_ID('BENEFICIARIO') IS NOT NULL
    PRINT '<<< CREATED TABLE BENEFICIARIO >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE BENEFICIARIO >>>'
go

/* 
 * TABLE: CONTACORRENTE 
 */

CREATE TABLE CONTACORRENTE(
	ID                varchar(36) NOT NULL,
    AGENCIA    varbinary(12)    NOT NULL,
    CONTA      varchar(10)      NOT NULL,
    TITULAR    varchar(60)      NOT NULL,
    CONSTRAINT PK_CONTACORRENTE PRIMARY KEY NONCLUSTERED (ID)
)
go



IF OBJECT_ID('CONTACORRENTE') IS NOT NULL
    PRINT '<<< CREATED TABLE CONTACORRENTE >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE CONTACORRENTE >>>'
go

/* 
 * TABLE: DUPLICATA 
 */

CREATE TABLE DUPLICATA(
	ID                varchar(36) NOT NULL,
    DOCUMENTO           varchar(20)       NOT NULL,
    CODBENEFICIARIO     varchar(36)               NOT NULL,
    VALORPREVISTO       numeric(12, 2)    DEFAULT 0 NOT NULL,
    MULTA               numeric(12, 2)    DEFAULT 0 NOT NULL,
    DESCONTO            numeric(12, 2)    DEFAULT 0 NOT NULL,
    JUROS               numeric(12, 2)    DEFAULT 0 NOT NULL,
    VALORTOTAL          numeric(12, 2)    DEFAULT 0 NOT NULL,
    DATAVENCIMENTO      date              NULL,
    DATAPAGAMENTO       date              NULL,
    CODCONTACORRENTE    varchar(36)               NULL,
    CODPLANOCONTA       varchar(36)               NULL,
    CONSTRAINT PK_DUPLICATA PRIMARY KEY NONCLUSTERED (ID)
)
go



IF OBJECT_ID('DUPLICATA') IS NOT NULL
    PRINT '<<< CREATED TABLE DUPLICATA >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE DUPLICATA >>>'
go

/* 
 * TABLE: EVENTOS 
 */

CREATE TABLE EVENTOS(
	ID                varchar(36) NOT NULL,
    CODMINISTERIO     varchar(36)              NOT NULL,
    TITULO            varchar(500)     NOT NULL,
    DESCRICAO         varchar(5000)    NOT NULL,
    DATA              date             NOT NULL,
    LOCAL             varchar(300)     NOT NULL,
    HORARIO           time(7)          NOT NULL,
    BANNER            image            NULL,
    PRIVADO           varchar(1)       DEFAULT '0' NULL,
    PASTORPRESENTE    varchar(1)       DEFAULT '1' NULL,
    CONSTRAINT PK_EVENTO PRIMARY KEY NONCLUSTERED (ID)
)
go



IF OBJECT_ID('EVENTOS') IS NOT NULL
    PRINT '<<< CREATED TABLE EVENTOS >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE EVENTOS >>>'
go

/* 
 * TABLE: FORMAPAGAMENTO 
 */
 

CREATE TABLE FORMAPAGAMENTO(
	ID                varchar(36) NOT NULL,
    DESCRICAO    varchar(40)    NOT NULL,
    CONSTRAINT PK_FORMAPAGAMENTO PRIMARY KEY NONCLUSTERED (ID)
)
go



IF OBJECT_ID('FORMAPAGAMENTO') IS NOT NULL
    PRINT '<<< CREATED TABLE FORMAPAGAMENTO >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE FORMAPAGAMENTO >>>'
go

/* 
 * TABLE: IGREJA 
 */
 
CREATE TABLE IGREJA(
 	ID                varchar(36) NOT NULL,
    RAZAOSOCIAL     varchar(100)    NOT NULL,
    NOMEFANTASIA    varchar(60)     NULL,
    CNPJ            varchar(15)     NOT NULL,
    ENDERECO        varchar(100)    NULL,
    BAIRRO          varchar(60)     NULL,
    CIDADE          varchar(60)     NULL,
    NUMERO          varchar(8)      NULL,
    UF              varchar(2)      NOT NULL,
    CEP             varchar(10)     NOT NULL,
    TELEFONE        varchar(9)      NOT NULL,
    CELULAR         varchar(9)      NULL,
    RESPONSAVEL     varchar(100)    NOT NULL,
    LOCALIZACAO     varchar(100)    NULL,
    CONSTRAINT PK_IGREJA PRIMARY KEY NONCLUSTERED (ID)
)
go



IF OBJECT_ID('IGREJA') IS NOT NULL
    PRINT '<<< CREATED TABLE IGREJA >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE IGREJA >>>'
go

/* 
 * TABLE: INTEGRANTES 
 */

CREATE TABLE INTEGRANTES(
	ID                varchar(36) NOT NULL,
    CODBENEFICIARIO    varchar(36)           NOT NULL,
    CODMINISTERIO      varchar(36)           NOT NULL,
    ATIVO              varchar(1)    DEFAULT '1' NULL,
    CONSTRAINT PK_INTEGRANTES PRIMARY KEY NONCLUSTERED (ID)
)
go



IF OBJECT_ID('INTEGRANTES') IS NOT NULL
    PRINT '<<< CREATED TABLE INTEGRANTES >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE INTEGRANTES >>>'
go

/* 
 * TABLE: MENSAGEMENTRANTE 
 */

CREATE TABLE MENSAGEMENTRANTE(
	ID                varchar(36) NOT NULL,
    CODTIPOMENSAGEM    varchar(36)               NOT NULL,
    CODRESPONSAVEL     varchar(36)               NOT NULL,
    CODSOLICITANTE     varchar(36)               NOT NULL,
    NOMESOLICITANTE    varchar(100)      DEFAULT 'ANONIMO' NOT NULL,
    ASSUNTO            varchar(300)      NOT NULL,
    MENSAGEM           varchar(1000)    NOT NULL,
    EMAILCONTATO       varchar(150)      NOT NULL,
    PERMITERETORNO     varchar(1)        DEFAULT '1' NOT NULL,
    TELEFONECONTATO    varchar(16)       NULL,
    DATACONTATO        date              DEFAULT getdate() NULL,
    FREQUENTA          varchar(1)        DEFAULT '1' NULL,
    SITUACAO           varchar(1)       DEFAULT '1' NULL,
    CONSTRAINT PK_MENSAGEMENTRANTE PRIMARY KEY NONCLUSTERED (ID)
)
go



IF OBJECT_ID('MENSAGEMENTRANTE') IS NOT NULL
    PRINT '<<< CREATED TABLE MENSAGEMENTRANTE >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE MENSAGEMENTRANTE >>>'
go

/* 
 * TABLE: MENSAGEMSAINTE 
 */

CREATE TABLE MENSAGEMSAINTE(
	ID                varchar(36) NOT NULL,
    CODMINISTERIO          varchar(36)              NULL,
    CODTIPOMENSAGEM        varchar(36)              NOT NULL,
    MENSAGEM               varchar(1000)    NOT NULL,
    DATAENVIO              date             DEFAULT 'getdate()' NOT NULL,
    CODMENSAGEMENTRANTE    varchar(36)              NULL,
    CONSTRAINT PK_MENSAGEMSAINTE PRIMARY KEY NONCLUSTERED (ID)
)
go



IF OBJECT_ID('MENSAGEMSAINTE') IS NOT NULL
    PRINT '<<< CREATED TABLE MENSAGEMSAINTE >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE MENSAGEMSAINTE >>>'
go

/* 
 * TABLE: MINISTERIOS 
 */
 
 CREATE TABLE MINISTERIOS(
	ID                varchar(36) NOT NULL,
    CODRESPONSAVEL    varchar(36)              NOT NULL,
    NOME              varchar(100)     NOT NULL,
    DESCRICAO         varchar(1000)    NULL,
    CONSTRAINT PK_MINISTERIO PRIMARY KEY NONCLUSTERED (ID)
)
go



IF OBJECT_ID('MINISTERIOS') IS NOT NULL
    PRINT '<<< CREATED TABLE MINISTERIOS >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE MINISTERIOS >>>'
go

/* 
 * TABLE: OCORRENCIAENTRANTE 
 */

CREATE TABLE OCORRENCIAENTRANTE(
	ID                varchar(36) NOT NULL,
    CODMENSAGEMENTRANTE    varchar(36)              NOT NULL,
    CODRESPONSAVEL         varchar(36)              NOT NULL,
    DESCRICAO              varchar(1000)    NOT NULL,
    DATA                   datetime         NOT NULL,
    CONSTRAINT PK_OPCORRENCIAENTRANTE PRIMARY KEY NONCLUSTERED (ID)
)
go



IF OBJECT_ID('OCORRENCIAENTRANTE') IS NOT NULL
    PRINT '<<< CREATED TABLE OCORRENCIAENTRANTE >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE OCORRENCIAENTRANTE >>>'
go

/* 
 * TABLE: PARAMETROS 
 */

CREATE TABLE PARAMETROS(
	ID                varchar(36) NOT NULL,
    LOCALIZACAO              varchar(200)    NULL,
    EXIBIRLOCALIZACAO        varchar(3)      DEFAULT 'S' NOT NULL,
    CODPASTOR                varchar(36)             NULL,
    CODATENDIMENTON1         varchar(36) NULL,
    EMAILENTRANTE            varchar(80)     NULL,
    CONTATOSOMENTEMEMBROS    varchar(1)      DEFAULT '0' NULL,
    CONSTRAINT PK_PARAMETROS PRIMARY KEY NONCLUSTERED (ID)
)
go



IF OBJECT_ID('PARAMETROS') IS NOT NULL
    PRINT '<<< CREATED TABLE PARAMETROS >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE PARAMETROS >>>'
go

/* 
 * TABLE: PARTICIPANTES 
 */

CREATE TABLE PARTICIPANTES(
	ID                varchar(36) NOT NULL,
    SITUACAO           varchar(1)    DEFAULT '0' NOT NULL,
    CODBENEFICIARIO    varchar(36)            NOT NULL,
    CODEVENTO          varchar(36)            NOT NULL,
    LEMBRETE           varchar(1)     DEFAULT '0' NULL,
    CONSTRAINT PK26 PRIMARY KEY NONCLUSTERED (ID)
)
go



IF OBJECT_ID('PARTICIPANTES') IS NOT NULL
    PRINT '<<< CREATED TABLE PARTICIPANTES >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE PARTICIPANTES >>>'
go

/* 
 * TABLE: PEDIDOORACAO 
 */

CREATE TABLE PEDIDOORACAO(
	ID                varchar(36) NOT NULL,
    CODMENSAGEMENTRANTE    varchar(36)              NOT NULL,
    CODSOLICITANTE         varchar(36)              NULL,
    NOMESOLICITANTE        varchar(100)     NULL,
    DATASOLICITACAO        date             NULL,
    ASSUNTO                varchar(200)     NULL,
    DESCRICAO              varchar(1000)    NULL,
    DESCRICAOREVISADA      varchar(1000)    NULL,
    SITUACAO               varchar(1)      DEFAULT '1' NULL,
    CONSTRAINT PK_PEDIDOORACAO PRIMARY KEY NONCLUSTERED (ID)
)
go



IF OBJECT_ID('PEDIDOORACAO') IS NOT NULL
    PRINT '<<< CREATED TABLE PEDIDOORACAO >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE PEDIDOORACAO >>>'
go

/* 
 * TABLE: PLANOCONTA 
 */

CREATE TABLE PLANOCONTA(
	ID                varchar(36) NOT NULL,
    TIPO         varchar(1)     NULL,
    DESCRICAO    varchar(60)    NULL,
    CONSTRAINT PK_PLANOCONTA PRIMARY KEY NONCLUSTERED (ID)
)
go



IF OBJECT_ID('PLANOCONTA') IS NOT NULL
    PRINT '<<< CREATED TABLE PLANOCONTA >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE PLANOCONTA >>>'
go

/* 
 * TABLE: POSTAGEM 
 */

CREATE TABLE POSTAGEM(
	ID                varchar(36) NOT NULL,
    CODBENEFICIARIO    varchar(36)              NOT NULL,
    CODTOPICO          varchar(36)              NOT NULL,
    MENSAGEM           varchar(5000)    NOT NULL,
    DATAPUBLICACAO     date             NULL,
    CONSTRAINT PK_POSTAGEM PRIMARY KEY NONCLUSTERED (ID)
)
go



IF OBJECT_ID('POSTAGEM') IS NOT NULL
    PRINT '<<< CREATED TABLE POSTAGEM >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE POSTAGEM >>>'
go

/* 
 * TABLE: PROFISSAO 
 */

  
CREATE TABLE PROFISSAO(
	ID                varchar(36) NOT NULL,
    DESCRICAO    varchar(200)    NOT NULL,
    CONSTRAINT PK_PROFISSAO PRIMARY KEY NONCLUSTERED (ID)
)
go



IF OBJECT_ID('PROFISSAO') IS NOT NULL
    PRINT '<<< CREATED TABLE PROFISSAO >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE PROFISSAO >>>'
go

/* 
 * TABLE: PROGRAMACAO 
 */

CREATE TABLE PROGRAMACAO(
	ID                varchar(36) NOT NULL,
    CODIGREJA    varchar(36)             NOT NULL,
    TITULO       varchar(500)    NOT NULL,
    DESCRICAO    varchar(500)    NOT NULL,
    CONSTRAINT PK_PROGRAMACAO PRIMARY KEY NONCLUSTERED (ID)
)
go



IF OBJECT_ID('PROGRAMACAO') IS NOT NULL
    PRINT '<<< CREATED TABLE PROGRAMACAO >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE PROGRAMACAO >>>'
go

/* 
 * TABLE: TIPOMENSAGEM 
 */
CREATE TABLE TIPOMENSAGEM(
	ID                varchar(36) NOT NULL,
    TIPO         varchar(7)     NOT NULL,
    DESCRICAO    varchar(60)    NOT NULL,
    CONSTRAINT PK_DESTINOMENSAGEM PRIMARY KEY NONCLUSTERED (ID)
)
go



IF OBJECT_ID('TIPOMENSAGEM') IS NOT NULL
    PRINT '<<< CREATED TABLE TIPOMENSAGEM >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE TIPOMENSAGEM >>>'
go

/* 
 * TABLE: TOPICO 
 */

 
CREATE TABLE TOPICO(
	ID                varchar(36) NOT NULL,
    ASSUNTO         varchar(100)     NOT NULL,
    DESCRICAO       varchar(5000)    NOT NULL,
    DATACADASTRO    date             DEFAULT getdate() NOT NULL,
    CONSTRAINT PK_TOPICO PRIMARY KEY NONCLUSTERED (ID)
)
go



IF OBJECT_ID('TOPICO') IS NOT NULL
    PRINT '<<< CREATED TABLE TOPICO >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE TOPICO >>>'
go

/* 
 * TABLE: USUARIO 
 */

CREATE TABLE USUARIO(
	ID                varchar(36) NOT NULL,
    NOME     varchar(60)    NULL,
    LOGIN    varchar(15)    NULL,
    SENHA    varchar(10)    NULL,
    ATIVO    varchar(1)     NULL,
    CPF      varchar(13)    NULL,
    EMAIL    varchar(80)    NULL,
    CONSTRAINT PK_USUARIO PRIMARY KEY NONCLUSTERED (ID)
)
go



IF OBJECT_ID('USUARIO') IS NOT NULL
    PRINT '<<< CREATED TABLE USUARIO >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE USUARIO >>>'
go

/* 
 * TABLE: BAIXADUPLICATA 
 */

ALTER TABLE BAIXADUPLICATA ADD CONSTRAINT FK_DUPLICATA_BAIXA 
    FOREIGN KEY (CODDUPLICATA)
    REFERENCES DUPLICATA(ID)
go

ALTER TABLE BAIXADUPLICATA ADD CONSTRAINT FK_FORMAPAGTO_BAIXA 
    FOREIGN KEY (CODFORMAPAGAMENTO)
    REFERENCES FORMAPAGAMENTO(ID)
go


/* 
 * TABLE: BENEFICIARIO 
 */

ALTER TABLE BENEFICIARIO ADD CONSTRAINT FK_PROFISSAO_BENEFICIARIO 
    FOREIGN KEY (CODPROFISSAO)
    REFERENCES PROFISSAO(ID)
go


/* 
 * TABLE: DUPLICATA 
 */

ALTER TABLE DUPLICATA ADD CONSTRAINT FK_BENEFICIARIO_DUPLICATA 
    FOREIGN KEY (CODBENEFICIARIO)
    REFERENCES BENEFICIARIO(ID)
go

ALTER TABLE DUPLICATA ADD CONSTRAINT FK_CONTA_DUPLICATA 
    FOREIGN KEY (CODCONTACORRENTE)
    REFERENCES CONTACORRENTE(ID)
go

ALTER TABLE DUPLICATA ADD CONSTRAINT FK_PLANOCONTA_DUPLICATA 
    FOREIGN KEY (CODPLANOCONTA)
    REFERENCES PLANOCONTA(ID)
go


/* 
 * TABLE: EVENTOS 
 */

ALTER TABLE EVENTOS ADD CONSTRAINT FK_MINISTERIO_EVENTO 
    FOREIGN KEY (CODMINISTERIO)
    REFERENCES MINISTERIOS(ID)
go


/* 
 * TABLE: INTEGRANTES 
 */

ALTER TABLE INTEGRANTES ADD CONSTRAINT FK_BENEFICIARIO_INTEGRANTES 
    FOREIGN KEY (CODBENEFICIARIO)
    REFERENCES BENEFICIARIO(ID)
go

ALTER TABLE INTEGRANTES ADD CONSTRAINT FK_MINISTERIO_INTEGRANTE 
    FOREIGN KEY (CODMINISTERIO)
    REFERENCES MINISTERIOS(ID)
go


/* 
 * TABLE: MENSAGEMENTRANTE 
 */

ALTER TABLE MENSAGEMENTRANTE ADD CONSTRAINT FK_BENEF_MSGERESPONSAVEL 
    FOREIGN KEY (CODRESPONSAVEL)
    REFERENCES BENEFICIARIO(ID)
go

ALTER TABLE MENSAGEMENTRANTE ADD CONSTRAINT FK_BENEF_MSGESOLICITANTE 
    FOREIGN KEY (CODSOLICITANTE)
    REFERENCES BENEFICIARIO(ID)
go

ALTER TABLE MENSAGEMENTRANTE ADD CONSTRAINT FK_TIPOMSG_MSGENTRANTE 
    FOREIGN KEY (CODTIPOMENSAGEM)
    REFERENCES TIPOMENSAGEM(ID)
go


/* 
 * TABLE: MENSAGEMSAINTE 
 */

ALTER TABLE MENSAGEMSAINTE ADD CONSTRAINT FK_MINISTERIO_MSGSAINTE 
    FOREIGN KEY (CODMINISTERIO)
    REFERENCES MINISTERIOS(ID)
go

ALTER TABLE MENSAGEMSAINTE ADD CONSTRAINT FK_MSGE_MSGS 
    FOREIGN KEY (CODMENSAGEMENTRANTE)
    REFERENCES MENSAGEMENTRANTE(ID)
go

ALTER TABLE MENSAGEMSAINTE ADD CONSTRAINT FK_TIPOMSG_MSGSAINTE 
    FOREIGN KEY (CODTIPOMENSAGEM)
    REFERENCES TIPOMENSAGEM(ID)
go


/* 
 * TABLE: MINISTERIOS 
 */

ALTER TABLE MINISTERIOS ADD CONSTRAINT FK_BENEFICIARIO_MINISTERIOS 
    FOREIGN KEY (CODRESPONSAVEL)
    REFERENCES BENEFICIARIO(ID)
go


/* 
 * TABLE: OCORRENCIAENTRANTE 
 */

ALTER TABLE OCORRENCIAENTRANTE ADD CONSTRAINT FK_BENEF_OCORRENTRANTE 
    FOREIGN KEY (CODRESPONSAVEL)
    REFERENCES BENEFICIARIO(ID)
go

ALTER TABLE OCORRENCIAENTRANTE ADD CONSTRAINT FK_MENSAGEME_OCORRENCIA 
    FOREIGN KEY (CODMENSAGEMENTRANTE)
    REFERENCES MENSAGEMENTRANTE(ID)
go


/* 
 * TABLE: PARAMETROS 
 */

ALTER TABLE PARAMETROS ADD CONSTRAINT FK_BENEF_ATENDEN1 
    FOREIGN KEY (CODATENDIMENTON1)
    REFERENCES BENEFICIARIO(ID)
go

ALTER TABLE PARAMETROS ADD CONSTRAINT FK_BENEF_PARAMPASTOR 
    FOREIGN KEY (CODPASTOR)
    REFERENCES BENEFICIARIO(ID)
go


/* 
 * TABLE: PARTICIPANTES 
 */

ALTER TABLE PARTICIPANTES ADD CONSTRAINT FK_BENEF_PARTICIPANTES 
    FOREIGN KEY (CODBENEFICIARIO)
    REFERENCES BENEFICIARIO(ID)
go

ALTER TABLE PARTICIPANTES ADD CONSTRAINT FK_EVENTO_PARTICIPANTE 
    FOREIGN KEY (CODEVENTO)
    REFERENCES EVENTOS(ID)
go


/* 
 * TABLE: PEDIDOORACAO 
 */

ALTER TABLE PEDIDOORACAO ADD CONSTRAINT RefMENSAGEMENTRANTE56 
    FOREIGN KEY (CODMENSAGEMENTRANTE)
    REFERENCES MENSAGEMENTRANTE(ID)
go

ALTER TABLE PEDIDOORACAO ADD CONSTRAINT FK_BENEF_PEDIDOORACAO 
    FOREIGN KEY (CODSOLICITANTE)
    REFERENCES BENEFICIARIO(ID)
go


/* 
 * TABLE: POSTAGEM 
 */

ALTER TABLE POSTAGEM ADD CONSTRAINT FK_BENEFICIARIO_POSTAGEM 
    FOREIGN KEY (CODBENEFICIARIO)
    REFERENCES BENEFICIARIO(ID)
go

ALTER TABLE POSTAGEM ADD CONSTRAINT FK_TOPICO_POSTAGEM 
    FOREIGN KEY (CODTOPICO)
    REFERENCES TOPICO(ID)
go


/* 
 * TABLE: PROGRAMACAO 
 */

ALTER TABLE PROGRAMACAO ADD CONSTRAINT FK_IGREJA_PROGRAMACAO 
    FOREIGN KEY (CODIGREJA)
    REFERENCES IGREJA(ID)
go


